# Generated by Django 6.0.3 on 2026-04-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionitem",
            options={
                "permissions": [
                    ("can_view_action_item", "Can view action item"),
                    ("can_complete_action_item", "Can complete action item"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="meeting",
            options={
                "permissions": [
                    ("can_view_meeting", "Can view meeting"),
                    ("can_edit_meeting", "Can edit meeting"),
                    ("can_delete_meeting", "Can delete meeting"),
                ]
            },
        ),
        migrations.AddField(
            model_name="actionitem",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
